{-# LANGUAGE DataKinds #-}
{-# LANGUAGE OverloadedStrings #-}

-- | Validate and emit the static JavaScript product.
--
-- Parsing and writing are separate stages. The phase parameter on 'Scene'
-- makes it impossible to call 'writeSite' before 'validateScene' succeeds.
module Factory.Site
  ( renderIndexTemplate
  , validateScene
  , writeSite
  ) where

import Data.Aeson (encode, object, (.=))
import Data.ByteString.Lazy (toStrict)
import Data.List (nub)
import Data.Ratio ((%))
import Data.Set (Set)
import Factory.Domain
import System.Directory (copyFile, createDirectoryIfMissing)
import System.FilePath ((</>))
import qualified Data.ByteString as ByteString
import qualified Data.ByteString.Lazy as LazyByteString
import qualified Data.Set as Set
import qualified Data.Text as Text
import qualified Data.Text.IO as Text

validateScene :: Scene 'Unvalidated -> Either BuildError (Scene 'Validated)
validateScene scene
  | not (positiveFinite width) = Left (InvalidScene "board width must be finite and positive")
  | not (positiveFinite height) = Left (InvalidScene "board height must be finite and positive")
  | identifiers /= nub identifiers = Left (InvalidScene "asset identifiers must be unique")
  | any invalidAsset (sceneAssets scene) = Left (InvalidScene "asset dimensions must be positive")
  | any (referencesMissingAsset knownAssets) nodes = Left (InvalidScene "image node references a missing asset")
  | knownAssets /= referencedAssets = Left (InvalidScene "scene contains an unreferenced asset")
  | any (not . nodeIsFinite) (sceneContent scene) = Left (InvalidScene "scene contains a non-finite number")
  | any (not . nodeValuesAreValid) nodes = Left (InvalidScene "scene contains an invalid size, color, or opacity")
  | any (imageCoversBoard width height) nodes = Left (InvalidScene "a full-board raster image is not allowed")
  | otherwise =
      Right
        Scene
          { sceneWidth = sceneWidth scene
          , sceneHeight = sceneHeight scene
          , sceneAssets = sceneAssets scene
          , sceneContent = sceneContent scene
          }
  where
    width = unCoordinate (sceneWidth scene)
    height = unCoordinate (sceneHeight scene)
    identifiers = map assetId (sceneAssets scene)
    knownAssets = Set.fromList identifiers
    referencedAssets = Set.fromList [identifier | ImageNode identifier _ _ _ <- nodes]
    nodes = sceneContent scene

writeSite :: FilePath -> FilePath -> SiteTitle -> Scene 'Validated -> IO ()
writeSite templateDirectory outputDirectory title scene = do
  createDirectoryIfMissing True outputDirectory
  indexTemplate <- Text.readFile (templateDirectory </> "index.html")
  Text.writeFile (outputDirectory </> "index.html") (renderIndexTemplate title indexTemplate)
  copyFile (templateDirectory </> "runtime.js") (outputDirectory </> "runtime.js")
  copyFile (templateDirectory </> "styles.css") (outputDirectory </> "styles.css")
  ByteString.writeFile (outputDirectory </> "scene.generated.js") sceneModule
  LazyByteString.writeFile (outputDirectory </> "scene-summary.json") summary
  where
    sceneModule = "// Generated by Haskell. Do not edit this file by hand.\nexport const scene = Object.freeze(" <> toStrict (encode scene) <> ");\n"
    summary =
      encode
        ( object
            [ "width" .= unCoordinate (sceneWidth scene)
            , "height" .= unCoordinate (sceneHeight scene)
            , "assets" .= length (sceneAssets scene)
            , "images" .= countNodes isImage scene
            , "vectorArtworks" .= countNodes isVectorArtwork scene
            , "paths" .= countNodes isPath scene
            , "texts" .= countNodes isText scene
            , "links" .= countNodes isLink scene
            ]
        )

renderIndexTemplate :: SiteTitle -> Text.Text -> Text.Text
renderIndexTemplate title template =
  Text.intercalate renderedTitle (map renderAriaLabel (Text.splitOn "{{SITE_TITLE}}" template))
  where
    renderedTitle = escapeHtml (siteTitleText title)
    renderedAriaLabel = escapeHtml ("Zoomable page: " <> siteTitleText title)
    renderAriaLabel = Text.intercalate renderedAriaLabel . Text.splitOn "{{SITE_ARIA_LABEL}}"

escapeHtml :: Text.Text -> Text.Text
escapeHtml =
  Text.replace "'" "&#39;"
    . Text.replace "\"" "&quot;"
    . Text.replace ">" "&gt;"
    . Text.replace "<" "&lt;"
    . Text.replace "&" "&amp;"

nodeIsFinite :: SceneNode -> Bool
nodeIsFinite node = case node of
  ImageNode _ matrix opacity clips -> matrixIsFinite matrix && finite opacity && all clipIsFinite clips
  VectorArtworkNode shapes matrix opacity clips -> all vectorShapeIsFinite shapes && matrixIsFinite matrix && finite opacity && all clipIsFinite clips
  PathNode commands style clips -> all commandIsFinite commands && styleIsFinite style && all clipIsFinite clips
  TextNode run clips -> matrixIsFinite (textMatrix run) && finite (textFontSize run) && finite (textOpacity run) && all clipIsFinite clips
  LinkNode _ rectangle -> all finite [coordinate (rectX rectangle), coordinate (rectY rectangle), coordinate (rectWidth rectangle), coordinate (rectHeight rectangle)]
  where
    coordinate = unCoordinate

matrixIsFinite :: Matrix -> Bool
matrixIsFinite (Matrix a b c d e f) = all finite [a, b, c, d, e, f]

finite :: Double -> Bool
finite value = not (isNaN value || isInfinite value)

positiveFinite :: Double -> Bool
positiveFinite value = finite value && value > 0

invalidAsset :: Asset -> Bool
invalidAsset asset = assetWidth asset <= 0 || assetHeight asset <= 0

referencesMissingAsset :: Set AssetId -> SceneNode -> Bool
referencesMissingAsset identifiers (ImageNode identifier _ _ _) = Set.notMember identifier identifiers
referencesMissingAsset _ _ = False

nodeValuesAreValid :: SceneNode -> Bool
nodeValuesAreValid node = case node of
  ImageNode _ _ opacity _ -> unitInterval opacity
  VectorArtworkNode shapes _ opacity _ -> not (null shapes) && unitInterval opacity && all vectorShapeIsValid shapes
  PathNode _ style _ -> paintLineWidth style >= 0 && paintMiterLimit style >= 1 && validDashArray (paintDashArray style) && unitInterval (paintOpacity style) && maybe True (colorIsValid . fst) (paintFill style) && maybe True colorIsValid (paintStroke style)
  TextNode run _ -> textFontSize run > 0 && unitInterval (textOpacity run)
  LinkNode _ rectangle -> unCoordinate (rectWidth rectangle) > 0 && unCoordinate (rectHeight rectangle) > 0

unitInterval :: Double -> Bool
unitInterval value = value >= 0 && value <= 1

validDashArray :: [Double] -> Bool
validDashArray values = all (>= 0) values && (null values || any (> 0) values)

colorIsValid :: Color -> Bool
colorIsValid color = all unitInterval [colorRed color, colorGreen color, colorBlue color]

styleIsFinite :: PaintStyle -> Bool
styleIsFinite style =
  finite (paintLineWidth style)
    && finite (paintMiterLimit style)
    && all finite (paintDashArray style)
    && finite (paintDashPhase style)
    && finite (paintOpacity style)
    && maybe True (colorIsFinite . fst) (paintFill style)
    && maybe True colorIsFinite (paintStroke style)

colorIsFinite :: Color -> Bool
colorIsFinite color = all finite [colorRed color, colorGreen color, colorBlue color]

vectorShapeIsFinite :: VectorShape -> Bool
vectorShapeIsFinite shape = colorIsFinite (vectorColor shape) && finite (vectorOpacity shape)

vectorShapeIsValid :: VectorShape -> Bool
vectorShapeIsValid shape = not (Text.null (unVectorPath (vectorPath shape))) && colorIsValid (vectorColor shape) && unitInterval (vectorOpacity shape)

clipIsFinite :: ClipPath -> Bool
clipIsFinite = all commandIsFinite . clipCommands

commandIsFinite :: PathCommand -> Bool
commandIsFinite command = case command of
  MoveTo point -> pointIsFinite point
  LineTo point -> pointIsFinite point
  CurveTo first second end -> all pointIsFinite [first, second, end]
  ClosePath -> True

pointIsFinite :: Point BoardSpace -> Bool
pointIsFinite point = all (finite . unCoordinate) [pointX point, pointY point]

imageCoversBoard :: Double -> Double -> SceneNode -> Bool
imageCoversBoard boardWidth boardHeight (ImageNode _ matrix _ _) =
  determinant /= 0 && all inside [(0, 0), (width, 0), (0, height), (width, height)]
  where
    a = toRational (matrixA matrix)
    b = toRational (matrixB matrix)
    c = toRational (matrixC matrix)
    d = toRational (matrixD matrix)
    e = toRational (matrixE matrix)
    f = toRational (matrixF matrix)
    width = toRational boardWidth
    height = toRational boardHeight
    determinant = a * d - b * c
    inside (x, y) =
      let offsetX = x - e
          offsetY = y - f
          unitX = (d * offsetX - c * offsetY) / determinant
          unitY = (a * offsetY - b * offsetX) / determinant
       in unitX >= -coverageTolerance
            && unitX <= 1 + coverageTolerance
            && unitY >= -coverageTolerance
            && unitY <= 1 + coverageTolerance
imageCoversBoard _ _ _ = False

coverageTolerance :: Rational
coverageTolerance = 1 % 1000000000

countNodes :: (SceneNode -> Bool) -> Scene phase -> Int
countNodes predicate = length . filter predicate . sceneNodes

isImage, isVectorArtwork, isPath, isText, isLink :: SceneNode -> Bool
isImage ImageNode {} = True
isImage _ = False
isVectorArtwork VectorArtworkNode {} = True
isVectorArtwork _ = False
isPath PathNode {} = True
isPath _ = False
isText TextNode {} = True
isText _ = False
isLink LinkNode {} = True
isLink _ = False
